### ISSUE TITLE
Add extra samples

### ISSUE THREAD

**Issue by MarkStokes** [OfficeDev/O365-WebApp-MultiTenant#10]
Could we extend this application to include additional API samples?

Whilst the contacts sample works, my dev(s) have so far been unsuccessful in being able to run a simple search query via the API off the back of this sample.  We keep getting errors around unable to silently get the token.

I have a feeling that the ADALTokenCache implementation may be an issue, it certainly seems to be when you try and host this in Azure from what I have heard from others.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
