### ISSUE TITLE
2 issues noted

### ISSUE THREAD

**Issue by ramakrpr** [OfficeDev/O365-WebApp-MultiTenant#13]
1. Helper class - SettingsHelper.cs
   Had to update "_appKey" value to use "ida:ClientSecret". There is no "ida:AppKey" reference in web.config
2. Had to re-create the a new mdf file instead of the one in package - existing was giving read-only error to the database while updating the token cache

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
