### ISSUE TITLE
How to access graph api

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/O365-WebApp-MultiTenant#15]
Hi, 
i wanted to access the Microsoft graph API for one drive using this application, and i could do it for one tenant using the access token i got and also adding Microsoft graph application in azure list of the application this app should access giving necessary rights. I noticed that this application works fine for one tenant, but for other tenant i could only sign in and get the access token, but i could not do the operation using Microsoft graph API. when i use that access token in postman, and query the graph api, i could get the root level access and it tells me how many documents it has but if i try to list down all the children using 
https://graph.microsoft.com/v1.0/me/drive/root/children this api, it gives me empty result. also in java-script jquery file, the call is succeeding but in network tab of google chrome, it says unauthorized user..what could be the issue.

token is same in following image, but behavior is different

network tab in chrome
![image](https://cloud.githubusercontent.com/assets/10468130/16393934/9ebbe368-3c67-11e6-9ae6-2cdf1c5951c2.png)

postman tool

![image](https://cloud.githubusercontent.com/assets/10468130/16393967/c6319474-3c67-11e6-81f5-4c5c49153fec.png)

**Comment by shyambhiogade** [comment]
i noticed that if i provide the domain name in web.config of another user it works. but if i need to provide domain name for each tenant, how can we says its a multi-tenant application.

you see the commented ida:Domain value, only after adding such values for each tenant i found its working...can someone guide me how to make it work truly for multitenant.

![image](https://cloud.githubusercontent.com/assets/10468130/16397175/a291e554-3c77-11e6-824b-11be7700b8b4.png)

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
