### ISSUE TITLE
getting error https://graph.windows.com was not found in the tenant

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/O365-WebApp-MultiTenant#16]
hi, 
I am trying to use the access token generated by this application, this application uses graph url as https://graph.windows.net, if i use this url with graph api in postman, it doesnt work. but if i use https://graph.windows.com and access token from this application, it works.

after taking the latest source code and replacing the https://graph.windows.net with https://graph.windows.com, i am getting the application error as https://graph.windows.com is not registered with tenant..can someone tell me whats the issue. please check the error, 

![image](https://cloud.githubusercontent.com/assets/10468130/16395805/875a2f28-3c70-11e6-8486-a48656fcbb53.png)

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
