### ISSUE TITLE
Error - Could not resolve capability 'Contacts'

### ISSUE THREAD

**Issue by beauholland** [OfficeDev/O365-WebApp-MultiTenant#2]
Error - "Could not resolve capability 'Contacts'."
![error](https://cloud.githubusercontent.com/assets/4987869/5520957/1382171e-89de-11e4-9828-2e23dafc1bae.png)

ContactsController.cs - line 53

```
var dcr = await discClient.DiscoverCapabilityAsync("Contacts");
```

**Comment by MarkStokes** [comment]
I am also getting this error. I did initially consent the app without the Contacts permissions.. so want to reconsent.

I will need to do this a few times as I add "stuff" to my project... so what is the right way to force a re-consent?

**Comment by fkof** [comment]
I have the same error, but I can't resolve, help please

**Comment by Divyeshkotadia** [comment]
Hi All,

I faced the same issue and scratched my head for more than 24 hrs. Tried different techniques and available O365 samples but could not find a correct solution till this article came to rescue.
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview
In this article, the team has mentioned about revoking USER CONSENT and that resolved this issue for me. 

So to cut short please follow steps and you should be fine:
1) Login to https://myapps.microsoft.com/ location. 
2) It will have all application that has been granted some access. Find your application and remove it.
3) Now log out of your application (in my case it was .net MVC application) and close browser and revisit the application again.
4) Log in to your application and navigate to a page which makes API call.
5) It should prompt you for granting access. e.g. Read permission for contacts, click yes and wohla your good to go. 

Hope this helps someone like who is new to this world.

Sharing is caring!!!

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
