### ISSUE TITLE
ADALTokenCache.AfterAccessNotification always creates new database entry

### ISSUE THREAD

**Issue by minustehbare** [OfficeDev/O365-WebApp-MultiTenant#20]
The code within [Models/AdalTokenCache.cs](https://github.com/OfficeDev/O365-WebApp-MultiTenant/blob/master/O365-WebApp-MultiTenant/O365-WebApp-MultiTenant/Models/ADALTokenCache.cs) creates a new instance of UserTokenCache without checking for the existence of a cached value.  The resulting `EntityState` is therefore always `EntityState.Added`, causing records to be inserted rather than updating the existing entry.

```
if (this.HasStateChanged)
{
  Cache = new UserTokenCache
  {
    webUserUniqueId = User,
    cacheBits = this.Serialize(),
    LastWrite = DateTime.Now
  };
  //// update the DB and the lastwrite
  db.Entry(Cache).State = Cache.UserTokenCacheId == 0 ? EntityState.Added : EntityState.Modified;
  db.SaveChanges();
  this.HasStateChanged = false;
}
```

[Similar issues](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-multitenant-openidconnect/pull/31) issues have been resolved in other repositories.  Will submit a pull request if desired.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
