### ISSUE TITLE
I can't sign in using an account from other tenants

### ISSUE THREAD

**Issue by fabioluz** [OfficeDev/O365-WebApp-MultiTenant#3]
I followed all the instructions... everything works fine, but only when I sign-in using an account registered in the same tenant of the app's tenant.

When I try to sign-in using an account from others tenant, I get an "access_denied" error.

Any ideas?

**Comment by chakkaradeep** [comment]
@fabioluz - Can you login to your tenant's Azure AD Portal and check to see if the app is actually enabled for multi-tenant?

**Comment by fabioluz** [comment]
Yeah, multi-tenant is activated. 

When I try to sign-in using an account from others tenants, I get the access_denied. I don't even get the Consent page, I think that's why I get an "access_denied". 

I tried to call Account/Consent method, without success, this error returned in the URL: error_description=AADSTS65005%3a+The+application+needs+access+to+a+service+that+your+organization+coniotest+has+not+subscribed+to.+Please+contact+your+Administrator+to+review+the+configuration+of+your+service+subscriptions.%0d%0aTrace+ID%3a+b51fdec1-4c94-4412-bf0a-7548daec5149%0d%0aCorrelation+ID%3a+cfa4fa3c-2cdd-4ac4-b5ab-7657c895a8eb%0d%0aTimestamp%3a+2015-01-16+23%3a43%3a49Z

![error](https://cloud.githubusercontent.com/assets/5049361/5786245/f8462f4a-9dc8-11e4-8e78-ffa7aae48513.png)

**Comment by fabioluz** [comment]
I solved the problem.

My tenant has the application Office 365 Exchange Online, but my test tenant don't. That's why I can't sign in using a user of my test tenant. The test tenant needs the Office 365 Exchange Online installed.

I kinda obvious but I didn't think about that.

Thank you.
