### ISSUE TITLE
We need to have better comments for exception exceptions.

### ISSUE THREAD

**Issue by brentschmaltz** [OfficeDev/O365-WebApp-MultiTenant#4]
Users are blindly following this code and swallowing errors.

93                         AuthenticationFailed = (context) => 
94                         { 
95                             // Suppress the exception if you don't want to see the error 
96                             context.HandleResponse(); 
97                             return Task.FromResult(0); 
98                         }

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
