### ISSUE TITLE
AuthKey => ClientSecret

### ISSUE THREAD

**Issue by bobbyware** [OfficeDev/O365-WebApp-MultiTenant#7]
SettingsHelper:

private static string _appKey = ConfigurationManager.AppSettings["ida:AppKey"] ?? ConfigurationManager.AppSettings["ida:Password"];

must be:

private static string _appKey = ConfigurationManager.AppSettings["ida:ClientSecret"] ?? ConfigurationManager.AppSettings["ida:Password"];

as the setting is the ClientSecret, not AppKey.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
