### ISSUE TITLE
Connected service (skip)

### ISSUE THREAD

**Issue by cosmincalin** [OfficeDev/O365-WebApp-MultiTenant#8]
Hi,
I saw that in order to get the sign in function to work, before we start the app, we need to add a connected service and then to register the app with on drive business email. There is any possibility to skip that part and only to add the connected service and when the user try to log in to register then the app ? Or a method to skip that register app part (to do it from code or something like this) ?

Thanks

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
